project_metadata:
  package: GDGUkraine

global:
  environment: production
  engine.url_for.on: true
  engine.logging.on: true
  engine.sqlalchemy.on: true
  engine.oauth.on: true
  google_oauth:
    id: <google_app_id>.apps.googleusercontent.com
    secret: <google_app_secret>
    scope:
        - https://www.googleapis.com/auth/userinfo.email
        - https://www.googleapis.com/auth/userinfo.profile
        # Send an email message:
        - https://www.googleapis.com/auth/gmail.compose
        # Create a new file on Google Drive
        - https://www.googleapis.com/auth/drive.file
  #tools.trailing_slash.on: false
  base_app_url: &base_url https://gdg.org.ua
  tools.proxy.on: true
  tools.proxy.base: *base_url
  alembic:
    script_location: src/db
    sqlalchemy.url: &db_url mysql+mysqlconnector://dbuser:dbpwd@/dbname?unix_socket=/var/run/mysqld/mysqld.sock

controllers:
  '':
    controller: !!python/name:GDGUkraine.controller.Root
    /:
      tools.proxy.on: true
      tools.orm_session.on: true
      tools.sessions.on: true
      tools.sessions.storage_type: file
      tools.sessions.storage_path: .sessions
      tools.staticdir.root: static
      tools.staticfile.root: static
    /css:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: css
    /js:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: js
    /img:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: img
    /libs:  # Path for third-party libs, bower_components etc.
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: libs
    /admin:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: templates/admin/admin.html
    /templates:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: templates
    /favicon.ico:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: favicon.ico
    /google55b33f78b4c8d4c6.html:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: google55b33f78b4c8d4c6.html
  /api:
    controller: !!python/name:GDGUkraine.rest_controller.rest_api
    /:
      request.dispatch: !!python/name:GDGUkraine.rest_controller.rest_api
      request.error_response: !!python/name:GDGUkraine.rest_controller.unexpected_error_handler
      error_page.default: !!python/name:GDGUkraine.rest_controller.generic_error_handler
      tools.orm_session.on: true
      tools.sessions.on: true
  /events:
    controller: !!python/name:GDGUkraine.events_controller.events
    /:
      request.dispatch: !!python/name:GDGUkraine.events_controller.events
      tools.orm_session.on: true
      tools.sessions.on: true

sqlalchemy_engine:
  url: *db_url
  pool_recycle: 60

jinja2:
  loader: !!python/object:jinja2.loaders.FileSystemLoader
          encoding: utf-8
          searchpath: [src/GDGUkraine/templates]
  bytecode_cache: !!python/object:jinja2.bccache.FileSystemBytecodeCache {directory: .cache,
                                                                          pattern: __jinja2_%s.cache}
  auto_reload: false
  use_webassets: true
  globals:
    url_for: !!python/name:GDGUkraine.lib.utils.url.url_for
    url_for_class: !!python/name:GDGUkraine.lib.utils.url.url_for_class
    url_for_routes: !!python/name:GDGUkraine.lib.utils.url.url_for_routes
    url_for_cp: !!python/name:GDGUkraine.lib.utils.url.url_for_cp
    url_for_static: !!python/name:GDGUkraine.lib.utils.url.url_for_static
