language: python
python: 3.5

# Environmental variables
env:
    # Marks build successful regardless of whether allowed-failures finished
    fast_finish: true

# Run in ubuntu-trusty environment
dist: trusty
sudo: required

# Cache .vagga images to speedup sequential builds
cache:
  timeout: 21600 # 6 hours
  pip: true
  directories:
   - .vagga/.roots
   - .vagga/.mnt
   - .vagga/.transient

# Scripts to install dependencies
# These are mostly honestly borrowed from https://github.com/tailhook/vagga/tree/master/.travis.yml
install:
  - 'echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml'
  - echo "$(id -un):100000:65536" | sudo tee /etc/subuid | sudo tee /etc/subgid
  - sudo apt-get install uidmap -y
  - curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh
  - vagga _build test
  # I did not find a way to run pre-commit inside vagga
  - pip install pre-commit

# Run tests
script:
  - vagga test --with-coverage --cover-package=GDGUkraine --cover-xml
  - pre-commit run --all-files

after_success: bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1001e872f956d15468ae
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
