language: python
python: 3.6

# Multienv testing
matrix:
  # Marks build successful regardless of whether allowed-failures finished
  fast_finish: true

# Run in ubuntu-trusty environment
dist: trusty
sudo: required

# OS packages
addons:
  apt:
    packages: [vagga]
    sources:
      - sourceline: >-
          deb [arch=amd64 trusted=yes] http://ubuntu.zerogw.com vagga-testing main

# Cache .vagga images to speedup sequential builds
cache:
  timeout: 21600 # 6 hours
  pip: true
  directories:
   - .vagga/.roots
   - .vagga/.mnt
   - .vagga/.transient

# Tell vagga to fetch ubuntu images from certain location
before_install: |
  cat > ~/.vagga.yaml <<VAGGA_CONFIG
  alpine-mirror: http://mirror.yandex.ru/mirrors/alpine/
  ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/
  VAGGA_CONFIG

install: vagga _build test

# Run tests and linters
script:
  - vagga lint
  - vagga test

after_success: bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1001e872f956d15468ae
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
