language: python
python: 3.5

# Scripts to install dependencies
install:
    - pip install tox

# Environmental variables
env:
    # These will be set always
    global:
        - >
            BLUEBERRYPY_CONFIG='{ "sqlalchemy_engine": { "url": "sqlite://" } }'

    # At least one build per one of the following variable
    matrix:
        - TOX_ENV=py34-codestyle,py34-nosetests
        - TOX_ENV=py35-codestyle,py35-nosetests

# Run tests
script:
    - tox -e $TOX_ENV
