language: python
python: 3.5

# Scripts to install dependencies
install:
    - chmod +x make.sh
    - ./make.sh test-env py35 # py35 here is for non-displaying of dialog

# Environmental variables
env:
    # Will be set always
    global:
        - BLUEBERRYPY_CONFIG='{}'

    # At least one build per one of the following variable
    matrix:
        - TOX_ENV=py34-codestyle,py34-nosetests
        - TOX_ENV=py35-codestyle,py35-nosetests

# Run tests
script:
    - TOX_ARGS="-e $TOX_ENV"
    - ./make.sh test-envs
