_base_job: &_base_job
  language: python
  python: 3.6

  # Multienv testing
  matrix:
    # Marks build successful regardless of whether allowed-failures finished
    fast_finish: true

  # Run in ubuntu-trusty environment
  dist: trusty
  sudo: required

  # OS packages
  addons:
    apt:
      packages: [vagga]
      sources:
      - sourceline: >-
          deb [arch=amd64 trusted=yes] http://ubuntu.zerogw.com vagga-testing main

  install: skip
  before_script: vagga --version
  script: skip

# Cleanup useless stuff: unused containers and all persistent volumes
before_cache:
- vagga _clean --unused --volumes
# Remove problematic folder, it's empty anyway:
- rm -rf .vagga/.cache/apt-cache/archives/partial

# Cache .vagga images to speedup sequential builds
cache:
  timeout: 21600 # 6 hours
  pip: true
  directories:
  - .travis/.vagga-cache
  - .vagga/.cache

jobs:
  include:
  - stage: build Vagga test container
    <<: *_base_job
    # Tell vagga to fetch ubuntu images from certain location
    before_install: cp -v .travis/.vagga.yaml ~/
    install: vagga _build test
    script: |
      vagga _push_image app &
      vagga _push_image test &
      wait
  - stage: &tests_label tests and linters
    <<: *_base_job
    script: vagga lint
  - stage: *tests_label
    <<: *_base_job
    install: pip install codecov
    script: vagga test
    after_success: bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    <<: *_base_job
    deploy:
      provider: script
      script: .travis/deploy.sh
      on:
        #all_branches: true
        branch: master
        python: 3.6
        #tags: true

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1001e872f956d15468ae
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  slack:
    secure: US4JF4c+qvMJ3I2eg7jEKpo/mloest1HNhZrVje+ZEtKz6mvpx2uzxBsQahBgbD1I/v2S09qSu7nhImjJNmCVji59c81pTLcuUS4FfvDtUlke3ie7K7hFZbB5MEWTjvGyKUTjrsvKjYvuFFIb09C/es+MBRNHY54JTT85Jkh3SM=

# vim:ft=yaml: et ts=2 sts=2 sw=2 tw=79 autoindent smartindent
