project_metadata:
  package: GDGUkraine

global:
  engine.url_for.on: true
  engine.logging.on: true
  engine.sqlalchemy.on: true
  #tools.trailing_slash.on: false
  base_app_url: http://localhost:8080
  alembic:
    # path to migration scripts
    script_location: src/db
    # template used to generate migration files
    # file_template: %%(rev)s_%%(slug)s

    # max length of characters to apply to the
    # "slug" field
    #truncate_slug_length: 40

    # set to 'true' to run the environment during
    # the 'revision' command, regardless of autogenerate
    # revision_environment: false

    # set to 'true' to allow .pyc and .pyo files without
    # a source .py file to be detected as revisions in the
    # versions/ directory
    # sourceless: false

    # version location specification; this defaults
    # to db/versions.  When using multiple version
    # directories, initial revisions must be specified with --version-path
    # version_locations: %(here)s/bar %(here)s/bat db/versions

    # the output encoding used when revision files
    # are written from script.py.mako
    # output_encoding: utf-8
    sqlalchemy.url: &db_url mysql+mysqlconnector://dbuser:dbpwd@/dbname?unix_socket=/var/run/mysqld/mysqld.sock

controllers:
  '':
    controller: !!python/name:GDGUkraine.controller.Root
    /:
      tools.orm_session.on: true
      tools.sessions.on: true
      tools.staticdir.root: static
      tools.staticfile.root: static
    /css:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: css
    /js:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: js
    /img:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: img
    /admin:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: templates/admin/admin.html
    /templates:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: templates
    /favicon.ico:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: favicon.ico
    /google55b33f78b4c8d4c6.html:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: google55b33f78b4c8d4c6.html
  /api:
    controller: !!python/name:GDGUkraine.rest_controller.rest_api
    /:
      request.dispatch: !!python/name:GDGUkraine.rest_controller.rest_api
      tools.orm_session.on: true
      tools.sessions.on: true
  /events:
    controller: !!python/name:GDGUkraine.events_controller.events
    /:
      request.dispatch: !!python/name:GDGUkraine.events_controller.events
      tools.orm_session.on: true
      tools.sessions.on: true

sqlalchemy_engine:
  url: *db_url
  #pool_recycle: 3600
  pool_recycle: 60

jinja2:
  loader: !!python/object:jinja2.loaders.FileSystemLoader
          encoding: utf-8
          searchpath: [src/GDGUkraine/templates]
  bytecode_cache: !!python/object:jinja2.bccache.FileSystemBytecodeCache {directory: .cache,
                                                                          pattern: __jinja2_%s.cache}
  auto_reload: true
  use_webassets: true
