project_metadata:
  package: GDGUkraine

global:
  engine.logging.on: true
  engine.sqlalchemy.on: true
  #tools.trailing_slash.on: false

controllers:
  '':
    controller: !!python/name:GDGUkraine.controller.Root
    /:
      tools.orm_session.on: true
      tools.sessions.on: true
      tools.staticdir.root: /home/gtug2/gdg.org.ua/static
      tools.staticfile.root: /home/gtug2/gdg.org.ua/static
    /css:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: css
    /js:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: js
    /img:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: img
    /admin:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: templates/admin/admin.html
    /templates:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: templates
    /favicon.ico:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: favicon.ico
    /google55b33f78b4c8d4c6.html:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: google55b33f78b4c8d4c6.html
  /api:
    controller: !!python/name:GDGUkraine.rest_controller.rest_api
    /:
      request.dispatch: !!python/name:GDGUkraine.rest_controller.rest_api
      tools.orm_session.on: true
      tools.sessions.on: true
  /events:
    controller: !!python/name:GDGUkraine.events_controller.events
    /:
      request.dispatch: !!python/name:GDGUkraine.events_controller.events
      tools.orm_session.on: true
      tools.sessions.on: true

sqlalchemy_engine:
  url: <connection uri here>
  #pool_recycle: 3600
  pool_recycle: 60

jinja2:
  loader: !!python/object:jinja2.loaders.FileSystemLoader
          encoding: utf-8
          searchpath: [/home/gtug2/gdg.org.ua/src/GDGUkraine/templates]
  bytecode_cache: !!python/object:jinja2.bccache.FileSystemBytecodeCache {directory: /home/gtug2/gdg.org.ua/.cache,
                                                                          pattern: __jinja2_%s.cache}
  auto_reload: true
  use_webassets: true
